dynamoose#984 Add SetContructor to support Schema Sets
dynamoose/dynamoose pull request #1022
Opened 2020-10-07 16:13 UTC by andrei-cdl

### Summary: 
Currently the type definition is missing `SetConstructor` which results in Type Error not allowing us query for Dynamodb Sets.

### GitHub linked issue: #984 
### Other information:
I'm not sure if there's another issue with Set or not but when I'm using it in my code base I'm noticing that the records returned from the Set are always empty `{}` not sure if it's related to this and even if Set is fully supported within this package.

I see in dynamoose 2.x documentation there's example of using set like the following:

``` js
{
    "friends": {
        "type": Set,
        "schema": [String]
    }
}
```

Currently TSC will complain

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #--- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [ ] No
- [x] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [ ] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [ ] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have ensured the following commands are successful from the root of the project directory
  - [x] `npm test`
  - [x] `npm run lint`
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

2020-10-09 00:16 UTC, fishcharlie requested changes
This needs tests in the `test/types` folder.

2020-10-14 13:44 UTC, andrei-cdl commented
Let me know if that's acceptable for the test case, if not let me know what else needs to addressed in regards to tests.

ty!

2020-10-22 03:18 UTC, andrei-cdl commented
@fishcharlie ~ if you have a chance to review and merge getting bot updating this to stale.

2020-11-16 00:20 UTC, fishcharlie commented on test/types/Schema.ts
> +
```suggestion
```

2020-11-16 00:20 UTC, fishcharlie approved these changes

2020-11-16 00:26 UTC, merged