Fix Schema typings
dynamoose/dynamoose pull request #1076
Opened 2020-12-12 04:12 UTC by andrewda

### Summary:

This PR updates the Schema typings to fix #1075. Adds `AttributeType[]` as a valid type for the `type` attribute and for the value of `SchemaDefinition`.

### GitHub linked issue:
Closes https://github.com/dynamoose/dynamoose/issues/1075

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I have ensured the following commands are successful from the root of the project directory
  - [x] `npm test`
  - [x] `npm run lint`
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/master/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

2020-12-12 15:46 UTC, fishcharlie requested changes
First of all, thanks so much for the PR! I think the biggest thing we need in order to merge this is automated tests. If you look in the `test/types` folder, you'll see a bunch of TypeScript tests that get type checked as part of our automated testing plan.

Write a few tests in there that fail without the changes you made, and pass with the changes you made.

2020-12-12 15:46 UTC, fishcharlie commented on lib/Schema.ts
> +	[attribute: string]: AttributeType | AttributeType[] | AttributeDefinition;
```suggestion
	[attribute: string]: AttributeType | AttributeType[] | AttributeDefinition | AttributeDefinition[];
```

2020-12-12 18:25 UTC, andrewda commented
Thanks @fishcharlie, not sure how I missed that! Just pushed some tests, let me know if there are any other changes you'd like to see :+1:

2020-12-13 00:29 UTC, fishcharlie approved these changes
Thanks so much for this!!

2020-12-13 00:34 UTC, merged