Fixing type of AttributeDefinition.default
dynamoose/dynamoose pull request #1381
Opened 2022-03-09 09:28 UTC by NakZMichael

### Summary:

When I use async function as default value,I got a type error.
This pull request fixes the bug.

### Code sample:
#### Schema

I got a type error on a scheme like below.

```
new dynamoose.Schema({
	"id": {
		"type": String,
		"default": () => Promise.resolve("foo")
	}
});
```

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [x] Test added to report bug (GitHub issue #---- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
-  [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

2022-04-11 02:00 UTC, fishcharlie commented
@andrewda Any chance you could review this?

2022-04-11 05:18 UTC, andrewda requested changes
Just a small styling change, looks good otherwise!

2022-04-11 05:18 UTC, andrewda commented on lib/Schema.ts
> +	default?: ValueType | (() => ValueType)|(() => Promise<ValueType>);
```suggestion
	default?: ValueType | (() => ValueType) | (() => Promise<ValueType>);
```

2022-06-11 22:20 UTC, fishcharlie requested changes
This needs to be added to the pending changelog.

2022-06-11 22:20 UTC, fishcharlie commented
Also merge conflicts need to be fixed.

2022-06-23 02:21 UTC, closed without merging