fix: add treatment when result.Items is not been returned using DAX
dynamoose/dynamoose pull request #1387
Opened 2022-04-01 20:41 UTC by estevanbc

fixes #1386

### Summary:

### Code sample:
#### Schema
```
// Code here
```

#### Model
```
// Code here
```

#### General
```
// Code here
```

### GitHub linked issue:

#----

### Other information:

### Type (select 1):
- [ ] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #---- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [ ] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [ ] Yes
- [ ] No

### Other:
- [ ] I have read through and followed the Contributing Guidelines
- [ ] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [ ] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [ ] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [ ] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [ ] I have filled out all fields above

2022-04-01 21:00 UTC, luciano-freitas approved these changes

2022-04-04 11:30 UTC, silvergutz approved these changes

2022-04-11 02:01 UTC, fishcharlie requested changes
Can we get some unit tests for this?

2022-06-11 22:18 UTC, fishcharlie commented
Closing as stale since @estevanbc never replied to my comment about adding tests.

2022-06-11 22:18 UTC, closed without merging

2023-03-21 12:39 UTC, arthurdarcet commented
this fixes a real bug that still exists. DAX won't return the `Items` key if the empty result for the query has been fetched from its cache