Hotfix:
dynamoose/dynamoose pull request #1430
Opened 2022-06-29 17:46 UTC by GuyGooL5

### Summary:
calling `dynamoose.aws.ddb.local()` was typed with a required parameter whereas it's actually optional (so says the docs and the code)

### Type (select 1):
- [X] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [ ] Test added to report bug (GitHub issue #---- @---)
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [X] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [ ] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [ ] Yes
- [ ] No

### Other:
- [ ] I have read through and followed the Contributing Guidelines
- [ ] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [ ] I have updated the Dynamoose documentation (if required) given the changes I made
- [ ] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [ ] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [ ] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [ ] I have filled out all fields above

2022-06-30 01:03 UTC, fishcharlie requested changes
This probably impacts v2 as well right? We probably want to merge it into the `v2` branch or make another PR to do so.

Also, this should have some tests under `tests/types` to ensure it doesn't happen again.

2022-06-30 09:12 UTC, GuyGooL5 commented
@fishcharlie just found that actually in v2 that the main function in `./lib/aws/ddb` doesn't supply types, they are simply inferred.

2022-07-02 15:18 UTC, fishcharlie commented
@GuyGooL5 Ok that is fine. Just write the test and we should be good to go here.

2022-07-09 17:21 UTC, fishcharlie approved these changes

2022-07-09 17:31 UTC, merged