TypeMismatch field to be of type object, instead found type object.
dynamoose/dynamoose pull request #1481
Opened 2022-08-25 13:51 UTC by halan

### Summary:

Currently, some libs use objects with null prototype to avoid function injection. The issue is explained here: https://github.com/graphql/graphql-js/issues/484#issuecomment-250344120.

Technically there are objects without a null prototype and they need to be recognized by Dynamoose schema. Without that, we'll have to deep copy those objects recovering the prototype (or just the `constructor = Object`).

It's a bug because those types are object and Dynamoose getting confused about that and raise a confused message:
> TypeMismatch: Expected {the name of the field} to be of type object, instead found type object.

I'm offering a safe and quick solution to recognize those objects and allow them to be stored on DynamoDB as regular objects.

### Code sample:
#### Schema
```ts
User = dynamoose.model("User", {
  "address": {
    "type": Object,
    "schema": {"country": String}
  }
});
```

#### General
```ts
user = new User({
  "address": Object.assign(Object.create(null), {"country": "world"})
});
// It will raise the weird Error: 
// TypeMismatch: Expected address to be of type object, instead found type object.

```

### Type (select 1):
- [x] Bug fix
- [ ] Feature implementation
- [ ] Documentation improvement
- [ ] Testing improvement

- [x] Test added to report bug 
- [ ] Something not listed here

### Is this a breaking change? (select 1):
- [ ] 🚨 YES 🚨
- [x] No
- [ ] I'm not sure

### Is this ready to be merged into Dynamoose? (select 1):
- [x] Yes
- [ ] No

### Are all the tests currently passing on this PR? (select 1):
- [x] Yes
- [ ] No

### Other:
- [x] I have read through and followed the Contributing Guidelines
- [x] I have searched through the GitHub pull requests to ensure this PR has not already been submitted
- [x] I have updated the Dynamoose documentation (if required) given the changes I made
- [x] I have added/updated the Dynamoose test cases (if required) given the changes I made
- [x] I agree that all changes made in this pull request may be distributed and are made available in accordance with the [Dynamoose license](https://github.com/dynamoose/dynamoose/blob/main/LICENSE)
- [x] All of my commits and commit messages are detailed, explain what changes were made, and are easy to follow and understand
- [x] I have filled out all fields above

2022-08-25 22:06 UTC, fishcharlie reviewed
@halan Can you please check to ensure we have a unit test that ensures that it fails if you try to use a class instance as an object type?

2022-08-26 01:43 UTC, halan commented
> @halan Can you please check to ensure we have a unit test that ensures that it fails if you try to use a class instance as an object type?

Probably not, all tests pass but my validation doesn't distinguish plain objects from class instances (yet).

I can add that test and improve the check. We can use `val.constructor === Object || val.constructor === undefined`, it can distinguish from classes instances. There is some ideas here https://github.com/jonschlinkert/is-plain-object/blob/master/is-plain-object.js. Tomorrow I add the test and improve the check.

2022-08-26 18:29 UTC, fishcharlie requested changes
Need to fix lint errors

2022-08-27 11:35 UTC, halan commented
Done

2022-08-27 21:27 UTC, fishcharlie approved these changes

2022-08-27 21:27 UTC, merged